import { useEffect,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import { toast } from 'sonner';
import ReactMarkdown from 'react-markdown';
import { ArrowRight,ArrowUpRight,Check,CheckCheck,LockKeyhole,Zap,Radio,Send,Sparkles,LoaderCircle,FileText,ExternalLink } from 'lucide-react';
import { api,errorText,money } from '../lib/api';
import { Modal,Action,Avatar,Empty } from '../components/Primitives';
import { MISSION_STAGES } from '../hooks/useMissionTracker';

export const NewMission=({id,world,wallet,navigate,refresh,onMissionStarted,catalog})=>{
 const a=world.agents.find(a=>a.id===id);const [text,setText]=useState(''),[busy,setBusy]=useState(false);
 const examples=Object.fromEntries(world.agents.map(agent=>[agent.category,catalog?.categories[agent.category]?.example||agent.strategy]));
 async function start(e){e.preventDefault();setBusy(true);try{const {data}=await api.post('/missions',{agentId:id,mission:text,mode:'live'});onMissionStarted(data);}catch(e){toast.error(errorText(e));setBusy(false);}}
 return <Modal title="A reason to work" subtitle="MISSION CONTROL / NEW OBJECTIVE" id="mission-create" onClose={()=>navigate('/agents/'+id)}>{!wallet||a?.creatorWallet!==wallet.id?<Empty title="Creator access only" description="Connect the identity that created this agent."/>:<form onSubmit={start}><div className="mission-agent"><Avatar avatar={a.avatar}/><div><b data-testid="mission-agent-name">{a.name}</b><small>{a.category} agent</small></div><span><Zap size={13}/>{a.energy}% energy</span></div><label htmlFor="mission-objective">Mission / objective</label><textarea id="mission-objective" data-testid="mission-objective" rows={5} value={text} maxLength={3000} minLength={10} required onChange={e=>setText(e.target.value)} placeholder="What should your agent discover? Include your criteria, timeframe, and preferred sources."/><button className="example-mission" type="button" data-testid="mission-example" onClick={()=>setText(examples[a.category])}><Sparkles size={13}/>Try a {a.category.toLowerCase()} mission<ArrowUpRight size={13}/></button><div className="mission-method"><span><Radio size={14}/>GPT-5.4 · MULTI-STAGE RESEARCH</span><p data-testid="mission-methodology">{a.strategy}</p><small>Your agent plans, gathers sources, analyzes evidence, and checks its claims before writing the result.</small></div><div className="mission-cost" data-testid="mission-cost"><span><Zap size={14}/>10% energy on completion</span><span>Results stay private</span></div>{!world.liveAI&&<p className="notice error" data-testid="mission-unavailable">The research engine is temporarily unavailable.</p>}<Action data-testid="mission-submit" className="full-width" type="submit" disabled={text.trim().length<10||a.status!=='ACTIVE'||!world.liveAI} busy={busy}><Send size={16}/>Launch mission</Action><p className="mission-launch-note" data-testid="mission-launch-note">Return to the world while your agent works. Its report opens when the research is complete.</p></form>}</Modal>;
};

export const MissionReport=({id,navigate,refresh,onMissionStarted})=>{
 const [m,setM]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;api.get('/missions/'+id).then(({data})=>{if(!alive)return;if(!['COMPLETED','FAILED'].includes(data.status)){onMissionStarted(data);return;}setM(data);refresh();}).catch(e=>{if(alive)setError(errorText(e));});return()=>{alive=false;};},[id,onMissionStarted,refresh]);
 const done=m?.status==='COMPLETED',failed=m?.status==='FAILED';
 async function keepPrivate(){try{await api.post('/missions/'+id+'/keep-private');toast.success('Report reviewed. Your work stays private.');}catch(e){toast.error(errorText(e));}}
 function share(){const summary=m.output.replace(/[#*`]/g,'').replace(/\s+/g,' ').trim().slice(0,180),text=`${m.mode==='demo'?'[Illustrative run] ':''}${m.agentName}: ${summary}\n\nvia Agent.ws`;window.open('https://twitter.com/intent/tweet?text='+encodeURIComponent(text.slice(0,275)),'_blank','noopener,noreferrer');}
 const elapsed=m?.completedAt?Math.round((new Date(m.completedAt)-new Date(m.startedAt))/1000):0;
 return <Modal title={done?'Work, worth keeping.':failed?'Mission interrupted':'Opening your work'} subtitle="PRIVATE WORK FEED / MISSION REPORT" id="report" wide onClose={()=>navigate('/')}>
  {error?<Empty title="Report unavailable" description={error}/>:!m?<div className="loading-state"><LoaderCircle className="spin"/>Opening the report…</div>:<>
   <div className="report-heading"><div><span className="execution-mode" data-testid="report-mode"><Radio size={13}/>{m.mode==='demo'?'ILLUSTRATIVE RUN · NO EXTERNAL RESEARCH':'RESEARCH COMPLETED · GPT-5.4'}</span><h3 data-testid="report-objective">{m.mission}</h3><p data-testid="report-agent">{m.agentName} · {new Date(m.startedAt).toLocaleString()}</p></div><LockKeyhole size={18}/></div>
   <div className="execution-pipeline" data-testid="execution-pipeline">{MISSION_STAGES.map((s,i)=><div data-testid={'execution-stage-'+i} className={done?'complete':''} key={s}><span>{done?<Check size={11}/>:i+1}</span><small>{s}</small></div>)}</div>
   <div className="report-status-line" data-testid="report-status"><span className={failed?'error-text':'green-text'}>{m.status}</span><span>{m.sources.length} sources · {Math.floor(elapsed/60)}m {elapsed%60}s</span></div>
   {failed&&<div className="notice error" data-testid="mission-error">{m.error}<br/>No energy consumed.</div>}
   {m.artifacts?.plan&&<details className="research-method" data-testid="research-method"><summary>Research plan & verification</summary><h4>Methodology</h4><ul>{(m.artifacts.plan.approach||[]).map((s,i)=><li key={i} data-testid={'research-plan-step-'+i}>{s}</li>)}</ul><h4>Verification pass</h4><p data-testid="research-verification">{m.artifacts.verification}</p></details>}
   {m.output&&<article className="report-markdown" data-testid="report-output"><ReactMarkdown components={{a:({node,...p})=><a {...p} target="_blank" rel="noopener noreferrer"/>}}>{m.output}</ReactMarkdown></article>}
   {m.sources.length>0&&<div className="report-sources"><h3>Sources retrieved</h3>{m.sources.map((s,i)=><a data-testid={'report-source-'+i} href={s.url} target="_blank" rel="noreferrer" key={s.url}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s.title}</b><small>{s.provider} · {new URL(s.url).hostname}</small></div><ExternalLink size={14}/></a>)}</div>}
   {done&&<><div className={'reward-result '+(m.rewardAmount>0?'found':'')} data-testid="mission-reward"><Sparkles size={23}/><div><b>{m.rewardAmount>0?'Discovery Reward found.':'A good day’s work.'}</b><p>{m.rewardAmount>0?'Recorded in your agent’s treasury.':'Your report and work history have been saved.'}</p></div>{m.rewardAmount>0&&<strong data-testid="reward-amount">+{money(m.rewardAmount)}<small>USDC</small></strong>}</div><div className="report-footer"><span><LockKeyhole size={13}/>Private until you choose otherwise.</span><Action secondary data-testid="report-keep-private" onClick={keepPrivate}><LockKeyhole size={14}/>Keep private</Action><Action data-testid="report-share-x" onClick={share}>𝕏 Post to X<ArrowUpRight size={14}/></Action></div></>}
   <button className="text-link" data-testid="report-back-agent" onClick={()=>navigate('/agents/'+m.agentId)}>Return to {m.agentName}<ArrowRight size={15}/></button>
  </>}
 </Modal>;
};

export const WorkFeed=({wallet,navigate})=>{
 const [missions,setMissions]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');const [params]=useSearchParams();const aid=params.get('agent'),owner=wallet?.id;
 useEffect(()=>{if(!owner){setLoading(false);return;}let alive=true;const load=()=>api.get(aid?'/agents/'+aid+'/missions':'/missions').then(r=>{if(alive){setMissions(r.data);setLoading(false);}}).catch(e=>{if(alive){setError(errorText(e));setLoading(false);}});load();const t=setInterval(load,4000);return()=>{alive=false;clearInterval(t);};},[owner,aid]);
 return <Modal title="The work behind the world" subtitle="WORK ARCHIVE / YOUR PRIVATE FEED" id="work-feed" wide onClose={()=>navigate('/')}><div className="feed-intro"><span><LockKeyhole size={15}/>Only visible to you</span><span data-testid="feed-count">{missions.length} missions</span></div>{!wallet?<Empty title="Your work stays yours" description="Connect your identity to open your agents’ private work feed." id="feed-wallet"><Action data-testid="feed-connect" onClick={()=>navigate('/wallet')}>Connect identity</Action></Empty>:loading?<div className="loading-state"><LoaderCircle className="spin"/>Opening the archive…</div>:error?<Empty title="Unable to load work" description={error}/>:!missions.length?<Empty id="feed-empty" title="Every story starts with a first mission" description="Give one of your agents an objective. Its results will appear here, not on your social accounts."><Action data-testid="feed-find-agent" onClick={()=>navigate('/agents')}>Find your agent<ArrowRight size={14}/></Action></Empty>:<div className="feed-list">{missions.map(m=><button data-testid={'feed-mission-'+m.id} className="feed-item" key={m.id} onClick={()=>navigate('/missions/'+m.id)}><span className="feed-icon">{m.status==='COMPLETED'?<CheckCheck size={21}/>:m.status==='FAILED'?<FileText size={21}/>:<LoaderCircle className="spin" size={21}/>}</span><div><div className="feed-meta"><span>{m.agentName}</span><small>{m.mode==='demo'?'ILLUSTRATIVE':'RESEARCH'}</small></div><h3>{m.mission}</h3><p>{m.status} · {m.sources.length} sources · {new Date(m.startedAt).toLocaleDateString()}</p></div><span className="feed-reward">{m.rewardAmount>0?'+'+money(m.rewardAmount)+' USDC':<LockKeyhole size={15}/>}<ArrowUpRight size={16}/></span></button>)}</div>}</Modal>;
};