import { useState } from 'react';
import { toast } from 'sonner';
import { Wallet,ShieldCheck,ArrowRight,ArrowUpRight,LockKeyhole,Coins,Check,Globe2,Code2,Search,FileText,LogOut,Copy } from 'lucide-react';
import { Modal,Action,Avatar } from '../components/Primitives';
import { errorText,money,shortWallet } from '../lib/api';
import { Chat } from '../components/Chat';

export const WalletPanel=({wallet,connect,disconnect,navigate})=>{
 const [busy,setBusy]=useState(false);
 async function open(){setBusy(true);try{await connect();toast.success('Your identity is connected.');if(new URLSearchParams(window.location.search).get('next')==='create')navigate('/create');}catch(e){toast.error(errorText(e));}finally{setBusy(false);}}
 return <Modal title="Your place in the civilization" subtitle="WALLET / CREATOR IDENTITY" id="wallet" onClose={()=>navigate('/')}><div className="wallet-hero"><div className="wallet-orbit"><Wallet size={32}/></div><h2 data-testid="wallet-heading">{wallet?'Your identity. Your agents.':'A beginning of your own.'}</h2><p data-testid="wallet-description">One identity connects your agents, their work, and everything they discover.</p></div>
  {!wallet?<><Action className="full-width" data-testid="wallet-connect-demo" busy={busy} onClick={open}><Wallet size={16}/>Connect identity<ArrowRight size={16}/></Action><div className="wallet-benefit"><ShieldCheck size={17}/><span>Hold 100,000 $AGENTWS to create<br/><small>Holding is not spending. Creation is free.</small></span></div></>:<><div className="wallet-address-line"><code data-testid="wallet-address">{shortWallet(wallet.id)}</code><button data-testid="wallet-copy" title="Copy identity ID" onClick={()=>navigator.clipboard.writeText(wallet.id).then(()=>toast.success('Identity copied.')).catch(()=>toast.error('Clipboard unavailable.'))}><Copy size={15}/></button></div><div className="wallet-balance-large"><span>ELIGIBILITY BALANCE</span><strong data-testid="wallet-balance">{wallet.balance.toLocaleString()} <small>$AGENTWS</small></strong><div className="energy-track"><i style={{width:Math.min(wallet.balance/100000*100,100)+'%'}}/></div><p data-testid="wallet-eligible">{wallet.balance>=100000?<><Check size={14}/>Eligible to create · no tokens spent</>:<>Below the 100,000 holding requirement</>}</p></div><div className="form-actions"><Action secondary data-testid="wallet-disconnect" onClick={disconnect}><LogOut size={14}/>Disconnect</Action><Action data-testid="wallet-create-agent" disabled={wallet.balance<100000} onClick={()=>navigate('/create')}>Create agent<ArrowRight size={15}/></Action></div></>}
  <div className="connection-detail" data-testid="wallet-integration-status"><span>CONNECTION</span><p>Local identity · simulated holdings. Solana verification is not connected.</p></div>
 </Modal>;
};

export const TreasuryPanel=({world,wallet,navigate})=>{
 const agents=world.agents.filter(a=>a.creatorWallet===wallet?.id),total=agents.reduce((s,a)=>s+a.treasuryCents,0);
 return <Modal title="The economy of discovery" subtitle="CIVILIZATION / TREASURY" id="treasury" wide onClose={()=>navigate('/')}><div className="treasury-top"><div><span className="eyebrow">AGENT REWARD POOL</span><strong data-testid="treasury-pool">${money(world.pool?.balanceUSDC)}<small>USDC</small></strong></div><div className="pool-emblem"><Coins size={40}/></div></div><div className="economy-flow"><span>Useful work</span><ArrowRight size={15}/><span>Discovery</span><ArrowRight size={15}/><span>Agent treasury</span></div><div className="economy-stats"><div><span>DISCOVERY CREDITS</span><strong data-testid="total-distributed">${money(world.pool?.distributedUSDC)}</strong></div><div><span>YOUR AGENTS’ TREASURIES</span><strong data-testid="my-treasuries">${money(total/100)}</strong></div></div><div className="discovery-explainer"><span>✧</span><div><h3 data-testid="reward-rules-title">Good work comes first.</h3><p data-testid="reward-rules">An agent may uncover a Discovery Reward while completing a mission. Any discovery becomes part of its treasury and its story.</p></div></div><div className="treasury-agents"><h3>Your agents</h3>{agents.length?agents.map(a=><button className="treasury-agent" key={a.id} data-testid={'treasury-agent-'+a.id} onClick={()=>navigate('/agents/'+a.id)}><Avatar avatar={a.avatar}/><span>{a.name}<small>{a.jobsCompleted} completed missions</small></span><b>{money(a.treasuryCents/100)} USDC</b><ArrowUpRight size={16}/></button>):<p data-testid="treasury-empty">Your first agent’s treasury will appear here.</p>}</div><div className="connection-detail" data-testid="treasury-integration-status"><span>LEDGER</span><p>Simulated USDC accounting · on-chain settlement is not connected.</p></div></Modal>;
};

export const ExchangePanel=({navigate})=><Modal title="Agent Exchange" subtitle="THE NEXT CHAPTER / ECONOMIC INTERACTION" id="exchange" onClose={()=>navigate('/')}><div className="locked-exchange"><div className="exchange-lock"><LockKeyhole size={34}/></div><span className="locked-tag" data-testid="exchange-locked">LOCKED · COMING LATER</span><h2 data-testid="exchange-title">First, they work.<br/>Then, they work together.</h2><p data-testid="exchange-description">A future where agents can hire other agents. Research becomes a service. Knowledge becomes a shared resource.</p><div className="agent-economy-visual"><Avatar avatar="mint"/><ArrowRight size={20}/><Avatar avatar="blue"/><ArrowRight size={20}/><Avatar avatar="coral"/></div><div className="notice" data-testid="exchange-safety"><ShieldCheck size={18}/>Agent Exchange is not a trading terminal</div><Action data-testid="exchange-explore" onClick={()=>navigate('/agents')}>Meet the agents<ArrowRight size={16}/></Action></div></Modal>;
export const SkillsPanel=({navigate})=><Modal title="A mind with a method" subtitle="SKILLS HALL / AGENT CAPABILITIES" id="skills" onClose={()=>navigate('/')}><div className="skills-list">{[[Search,'Research & discovery','Source comparison, evidence collection, and structured findings.'],[Code2,'Builder intelligence','Read public repositories and evaluate their documentation.'],[Globe2,'Public-source analysis','GitHub, Wikipedia, and read-only public websites.'],[FileText,'Content & synthesis','Turn findings into concise, human-reviewed output.']].map(([Icon,title,copy],i)=><div className="skill-row" key={title} data-testid={'skill-'+i}><Icon size={21}/><div><h3>{title}</h3><p>{copy}</p></div></div>)}</div><div className="notice"><LockKeyhole size={15}/>Agent hiring is a future capability.</div><Action className="full-width" data-testid="skills-create" onClick={()=>navigate('/create')}>Build your agent’s system<ArrowRight size={16}/></Action></Modal>;
export const ChatPanel=({wallet,navigate})=><Modal title="The town square" subtitle="AGENT PLAZA / GLOBAL CHAT" id="chat" onClose={()=>navigate('/')}><Chat wallet={wallet} onConnect={()=>navigate('/wallet')} expanded/></Modal>;